### ISSUE TITLE
Crash on root folders

### ISSUE THREAD

**Issue by NitroG42** [spacecowboy/NoNonsense-FilePicker#12] opened 2015-03-18 08:30 UTC
Using your library on my project (FDND), I found a little bug, it crashes when we go back to the / of the device, and then click on a folder which we can't access (I tried  on a device without root).
I'll probably make a pull request if you don't have the time.

Here's the stack trace : 

       java.lang.RuntimeException: An error occured while executing doInBackground()
                  at android.os.AsyncTask$3.done(AsyncTask.java:300)
                  at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                  at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                  at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                  at java.lang.Thread.run(Thread.java:818)
           Caused by: java.lang.NullPointerException: Attempt to get length of null array
                  at com.nononsenseapps.filepicker.FilePickerFragment$2.loadInBackground(FilePickerFragment.java:142)
                  at com.nononsenseapps.filepicker.FilePickerFragment$2.loadInBackground(FilePickerFragment.java:135)
                  at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
                  at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
                  at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
                  at android.os.AsyncTask$2.call(AsyncTask.java:288)
                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                  at java.lang.Thread.run(Thread.java:818)

**Comment by spacecowboy** [comment] 2015-03-22 22:41
Thanks for the bug report! I am pressed for time at the moment, so a pull request would be appreciated. Otherwise I'll have a look at it one or two months (probably).

**Comment by spacecowboy** [comment] 2015-04-21 14:58
Got some time so tried to reproduce this and failed.

Could you give an example where it fails? Navigating to for example /root does not crash it, it merely shows an empty screen.

**Comment by spacecowboy** [comment] 2015-04-22 22:06
Nevermind.. Will be fixed soon.

**Comment by NitroG42** [comment] 2015-04-24 07:41
Hi, sorry for the long delay. I didn't find time to work on my project or yours in the last weeks. Glad you could reproduce the crash.

**Comment by greenspand** [comment] 2015-04-27 17:28
Hi guys. How can I fix the problem. I really need to fix it till tomorrow because I will have to finish my project. Looking forward to your feedback.

**Comment by spacecowboy** [comment] 2015-04-27 17:33
@greenspand Try just catching the exception. Btw, where on the SD-card are you navigating to when you encounter this error?

**Comment by greenspand** [comment] 2015-04-27 17:36
When I browse the /data folder it stops and crashes.
Problem with catching the exception is that I don't get to catch it hence I am still in the File Explorer activity. when the issue occurs. Any workarounds?

**Comment by greenspand** [comment] 2015-04-27 17:36
The device used is a Samsung Tab 2 with ICS on. It's not the newest.

**Comment by spacecowboy** [comment] 2015-04-27 17:45
The code is actually already fixed, it's only the version up on MavenCentral which is a few commits behind. I'll update it.

**Comment by greenspand** [comment] 2015-04-27 17:53
Would it be possible if you could update it maybe today. I would really appreciate it. I just wanted to flattr you but I don't know how. I want to send a small amount.

**Comment by spacecowboy** [comment] 2015-04-27 19:53
I've just updated it on MavenCentral and it should be up in a few minutes. 

In your dependencies, change the minimum version to **1.2.0**

**Comment by spacecowboy** [comment] 2015-04-27 19:53
And please mention if it works or not

**Comment by spacecowboy** [comment] 2015-04-27 19:59
As a heads up, 2.0 will be released soon and will be backwards incompatible. So if you don't want your project to break in the coming days, fix the version to 1.2.0.

**Comment by greenspand** [comment] 2015-04-27 21:10
Awesome, it works. Thx for your help dude, you're awesome.Do you have like a paypal account our, how can I flattr.

**Comment by spacecowboy** [comment] 2015-04-27 22:09
Good to hear.

Just click the "Flattr this" link on the main page if you want to donate some beer money :)

**Closed by spacecowboy** 2015-04-27 22:09 UTC
Labels: bug

**Comment by greenspand** [comment] 2015-04-28 07:58
Will do that mate. Take care and happy coding.
